name: apk_extractor
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^1.3.1
  font_awesome_flutter: ^9.2.0
  get: ^4.3.8
  intl: ^0.17.0
  url_launcher: ^6.0.15
  share: ^2.0.4
  package_info: ^2.0.2
  flutter_rating_bar: ^4.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - images/ic_launcher.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove

  color: "#E3EBEC"
  image: images/ic_launcher.png
  color_dark: "#212230"
  image_dark: images/ic_launcher.png
  android_gravity: center
  fullscreen: true